version: "3.7"

services:
  app:
    container_name: foreign-exchange-currency
    image: foreign-exchange-currency
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
